configured_endpoints: 36
openapi_spec_url: https://storage.googleapis.com/stainless-sdk-openapi-specs/hubmap-consortium%2Fentity-python-sdk-19bccd5934f3874884a76dfe09b108be37f147cb2f0136fc84c588775884e929.yml
