configured_endpoints: 37
openapi_spec_url: https://storage.googleapis.com/stainless-sdk-openapi-specs/hubmap-consortium%2Fentity-python-sdk-cef289a4b569166a454722ef64219b669c478aea8d0ce26f88061bdb30364fd4.yml
