configured_endpoints: 36
openapi_spec_url: https://storage.googleapis.com/stainless-sdk-openapi-specs/hubmap-consortium%2Fentity-python-sdk-e8511f96ef8f0b96574c38e4dde5d6461c074f20091c88ed8ad29e1dddb35f6c.yml
